#
# Makefile for misc devices that really don't fit anywhere else.
#

ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor/2.0/core

obj-$(CONFIG_MTK_V4L2_LENS) += dw9781d.o
