# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/drivers/iommu
ccflags-y += -I$(srctree)/drivers/clk/mediatek/
ccflags-y += -I$(srctree)/include/soc/mediatek
ccflags-y += -I$(srctree)/drivers/iommu/arm/arm-smmu-v3/
obj-$(CONFIG_MTK_SMI) += mtk-smi-dbg.o

