# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hw_sem/

obj-$(CONFIG_MTK_HW_SEMAPHORE) += mtk-hw-semaphore.o
